name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          toolchain: stable
      - uses: actions-rs/clippy-check@v1
        with:
          args: -- -D warnings
          name: Clippy Results
          token: ${{ secrets.GITHUB_TOKEN }}
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--ignore-tests'
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          override: true
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          args: --all -- --check
          command: fmt
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
